services:
  db:
    image: postgres:16-alpine
    container_name: db_test_demlabs_shop
    restart: always
    env_file:
      - .env.test
    ports:
      - 5544:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5













