services:
  db:
    image: postgres:16-alpine
    container_name: db_demlabs_shop
    restart: always
#    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 5533:5432
    volumes:
      - db-demlabs-shop:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis_demlabs_shop
#    command: redis-server --requirepass so_secret
    restart: always
#    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - redis-demlabs-shop:/data
    ports:
      - 6699:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5


volumes:
  db-demlabs-shop:
    name: "db-demlabs-shop"
  redis-demlabs-shop:
    name: "redis-demlabs-shop"









